trigger:
  branches:
    include:
    - dev
    - release-*

jobs:
- job:
  strategy:
    matrix:
      macOS_azure:
        imageName: 'macOS-10.14'
        TILEDB_AZURE: ON
        CXX: clang++

  pool:
    vmImage: $(imageName)
  steps:
  - template: scripts/azure-linux_mac.yml
